/**
 * Locked Flue 2.0.3 build artifact surface: the Vite 8 + flue()/cloudflare() build never emits an
 * unguarded createRequire(import.meta.url) chunk (Workers rejects that pattern), the generated
 * dist/gestao/wrangler.json carries the Flue-owned surface (main + FLUE_GESTAO_BOT_V2_AGENT durable
 * object binding) alongside the authored D1 binding untouched, and the SPA client build lands
 * exactly where the authored wrangler.jsonc assets.directory expects it.
 * These tests VERIFY by actually running the build when dist/ is absent — they never pass
 * vacuously against a stale or missing artifact.
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DIST_DIR = resolve(ROOT, "dist");
const WORKER_DIST_DIR = resolve(DIST_DIR, "gestao");
const GENERATED_WRANGLER_JSON_PATH = resolve(WORKER_DIST_DIR, "wrangler.json");
const AUTHORED_WRANGLER_JSONC_PATH = resolve(ROOT, "wrangler.jsonc");

/** @description Full `npm run build` can take minutes on a cold checkout; give it headroom. */
const BUILD_TIMEOUT_MS = 10 * 60 * 1000;

/**
 * @description Strip // and block comments from JSONC so JSON.parse can read wrangler.jsonc.
 */
function parseJsonc(raw) {
  const stripped = raw
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
  return JSON.parse(stripped);
}

let hasEnsuredBuild = false;

/**
 * @description Shared build guarantee for every test in this file: if dist/ is absent, actually
 * run `npm run build` (never assume a stale/missing artifact means "pass") before any assertion
 * inspects the output. Idempotent across the three tests in this file.
 */
function ensureBuilt() {
  if (hasEnsuredBuild) return;
  if (!existsSync(DIST_DIR)) {
    execFileSync("npm", ["run", "build"], {
      cwd: ROOT,
      stdio: "inherit",
      timeout: BUILD_TIMEOUT_MS,
    });
  }
  hasEnsuredBuild = true;
}

/**
 * @description Recursively collect every .js file under a directory.
 */
function collectJsFilesRecursively(dir) {
  const results = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectJsFilesRecursively(full));
    } else if (entry.isFile() && entry.name.endsWith(".js")) {
      results.push(full);
    }
  }
  return results;
}

// ─── lt-flue2-no-unguarded-createrequire ───────────────────────────────────

test(
  "lt-flue2-no-unguarded-createrequire: no emitted dist/ chunk contains createRequire(import.meta.url)",
  { timeout: BUILD_TIMEOUT_MS },
  () => {
    ensureBuilt();
    assert.ok(
      existsSync(DIST_DIR),
      `dist/ must exist after ensuring the build ran, checked at ${DIST_DIR}`,
    );

    const jsFiles = collectJsFilesRecursively(DIST_DIR);
    assert.ok(
      jsFiles.length > 0,
      `the build must emit at least one .js chunk under ${DIST_DIR}, found none`,
    );

    for (const file of jsFiles) {
      const contents = readFileSync(file, "utf8");
      assert.equal(
        contents.includes("createRequire(import.meta.url)"),
        false,
        `emitted chunk ${file} must not contain the literal substring 'createRequire(import.meta.url)' — Workers rejects that pattern`,
      );
    }
  },
);

// ─── lt-flue2-generated-wrangler-has-flue-surface ──────────────────────────

test(
  "lt-flue2-generated-wrangler-has-flue-surface: generated wrangler.json has main + FLUE_GESTAO_BOT_V2_AGENT DO binding + authored DB binding",
  { timeout: BUILD_TIMEOUT_MS },
  () => {
    ensureBuilt();
    assert.ok(
      existsSync(GENERATED_WRANGLER_JSON_PATH),
      `generated wrangler.json must exist after the build, checked at ${GENERATED_WRANGLER_JSON_PATH}`,
    );

    const generated = JSON.parse(readFileSync(GENERATED_WRANGLER_JSON_PATH, "utf8"));

    assert.equal(
      typeof generated.main,
      "string",
      `generated wrangler.json 'main' must be a string entry generated by Flue, got type ${typeof generated.main}`,
    );
    assert.ok(
      generated.main.length > 0,
      "generated wrangler.json 'main' must be a non-empty string",
    );

    const bindings = generated.durable_objects?.bindings ?? [];
    assert.ok(
      Array.isArray(bindings),
      "generated wrangler.json durable_objects.bindings must be an array",
    );
    const flueBinding = bindings.find(
      (binding) =>
        binding &&
        typeof binding === "object" &&
        binding.name === "FLUE_GESTAO_BOT_V2_AGENT" &&
        binding.class_name === "FlueGestaoBotV2Agent",
    );
    assert.ok(
      flueBinding,
      `generated wrangler.json durable_objects.bindings must contain { name: 'FLUE_GESTAO_BOT_V2_AGENT', class_name: 'FlueGestaoBotV2Agent' }, got ${JSON.stringify(bindings)}`,
    );

    const authored = parseJsonc(readFileSync(AUTHORED_WRANGLER_JSONC_PATH, "utf8"));
    const authoredDbBinding = (authored.d1_databases ?? []).find(
      (db) => db && typeof db === "object" && db.binding === "DB",
    );
    assert.ok(
      authoredDbBinding,
      `authored wrangler.jsonc must declare a d1_databases entry with binding 'DB', got ${JSON.stringify(authored.d1_databases)}`,
    );

    const generatedDbBinding = (generated.d1_databases ?? []).find(
      (db) => db && typeof db === "object" && db.binding === "DB",
    );
    assert.ok(
      generatedDbBinding,
      `generated wrangler.json must carry the authored D1 binding named 'DB', got ${JSON.stringify(generated.d1_databases)}`,
    );
    assert.deepEqual(
      generatedDbBinding,
      authoredDbBinding,
      `generated wrangler.json's 'DB' d1_databases entry must pass through UNCHANGED from the authored wrangler.jsonc — expected ${JSON.stringify(authoredDbBinding)}, got ${JSON.stringify(generatedDbBinding)}`,
    );
  },
);

// ─── lt-flue2-spa-client-lands-where-wrangler-expects ──────────────────────

test(
  "lt-flue2-spa-client-lands-where-wrangler-expects: assets.directory from wrangler.jsonc exists and has index.html",
  { timeout: BUILD_TIMEOUT_MS },
  () => {
    ensureBuilt();
    const authored = parseJsonc(readFileSync(AUTHORED_WRANGLER_JSONC_PATH, "utf8"));
    const assetsDirectory = authored.assets?.directory;
    assert.equal(
      typeof assetsDirectory,
      "string",
      `wrangler.jsonc assets.directory must be a string, got type ${typeof assetsDirectory}`,
    );

    const clientDir = resolve(ROOT, assetsDirectory);
    assert.ok(
      existsSync(clientDir),
      `SPA client output directory ${clientDir} (from wrangler.jsonc assets.directory=${JSON.stringify(assetsDirectory)}) must exist after the build`,
    );

    const indexHtmlPath = join(clientDir, "index.html");
    assert.ok(
      existsSync(indexHtmlPath),
      `SPA client output directory ${clientDir} must contain index.html, checked at ${indexHtmlPath}`,
    );
  },
);
